import type { Branch } from "@/lib/types"

/**
 * The 30-branch Dhaka network from the tender. Order is stable: the demo's
 * deterministic datasets are seeded from `slug`, so renaming a branch
 * re-rolls its data while reordering this list does not.
 */
export const BRANCHES: Branch[] = [
  {
    id: "br_diabari",
    slug: "diabari",
    name: { en: "Diabari", bn: "দিয়াবাড়ি" },
    area: { en: "Uttara", bn: "উত্তরা" },
    kind: "flagship",
    capacity: 220,
    floorArea: 9240,
    openedAt: "2019-01-01",
    manager: { en: "Nusrat Jahan", bn: "নুসরাত জাহান" },
    phone: "+8801720000000",
    hue: "blue",
    initials: "D",
    status: "live",
    map: { x: 0.42, y: 0.06 },
  },
  {
    id: "br_uttara-sector-4",
    slug: "uttara-sector-4",
    name: { en: "Uttara Sector 4", bn: "উত্তরা সেক্টর ৪" },
    area: { en: "Uttara", bn: "উত্তরা" },
    kind: "standard",
    capacity: 150,
    floorArea: 6300,
    openedAt: "2020-06-02",
    manager: { en: "Tanvir Ahmed", bn: "তানভীর আহমেদ" },
    phone: "+8801823719411",
    hue: "teal",
    initials: "US",
    status: "live",
    map: { x: 0.46, y: 0.1 },
  },
  {
    id: "br_uttara-sector-7",
    slug: "uttara-sector-7",
    name: { en: "Uttara Sector 7", bn: "উত্তরা সেক্টর ৭" },
    area: { en: "Uttara", bn: "উত্তরা" },
    kind: "standard",
    capacity: 160,
    floorArea: 6720,
    openedAt: "2021-11-03",
    manager: { en: "Rubaiya Haque", bn: "রুবাইয়া হক" },
    phone: "+8801927438822",
    hue: "green",
    initials: "US",
    status: "live",
    map: { x: 0.5, y: 0.12 },
  },
  {
    id: "br_uttara-sector-11",
    slug: "uttara-sector-11",
    name: { en: "Uttara Sector 11", bn: "উত্তরা সেক্টর ১১" },
    area: { en: "Uttara", bn: "উত্তরা" },
    kind: "compact",
    capacity: 90,
    floorArea: 3780,
    openedAt: "2022-04-04",
    manager: { en: "Imran Kabir", bn: "ইমরান কবির" },
    phone: "+8801731158233",
    hue: "purple",
    initials: "US",
    status: "live",
    map: { x: 0.44, y: 0.15 },
  },
  {
    id: "br_mirpur-1",
    slug: "mirpur-1",
    name: { en: "Mirpur 1", bn: "মিরপুর ১" },
    area: { en: "Mirpur", bn: "মিরপুর" },
    kind: "standard",
    capacity: 140,
    floorArea: 5880,
    openedAt: "2023-09-05",
    manager: { en: "Sadia Rahman", bn: "সাদিয়া রহমান" },
    phone: "+8801834877644",
    hue: "magenta",
    initials: "M1",
    status: "live",
    map: { x: 0.28, y: 0.3 },
  },
  {
    id: "br_mirpur-2",
    slug: "mirpur-2",
    name: { en: "Mirpur 2", bn: "মিরপুর ২" },
    area: { en: "Mirpur", bn: "মিরপুর" },
    kind: "compact",
    capacity: 95,
    floorArea: 3990,
    openedAt: "2024-02-06",
    manager: { en: "Mahfuz Alam", bn: "মাহফুজ আলম" },
    phone: "+8801938597055",
    hue: "amber",
    initials: "M2",
    status: "live",
    map: { x: 0.25, y: 0.34 },
  },
  {
    id: "br_mirpur-10",
    slug: "mirpur-10",
    name: { en: "Mirpur 10", bn: "মিরপুর ১০" },
    area: { en: "Mirpur", bn: "মিরপুর" },
    kind: "flagship",
    capacity: 200,
    floorArea: 8400,
    openedAt: "2025-07-07",
    manager: { en: "Farzana Akter", bn: "ফারজানা আক্তার" },
    phone: "+8801742316466",
    hue: "rose",
    initials: "M1",
    status: "live",
    map: { x: 0.31, y: 0.27 },
  },
  {
    id: "br_mirpur-12",
    slug: "mirpur-12",
    name: { en: "Mirpur 12", bn: "মিরপুর ১২" },
    area: { en: "Mirpur", bn: "মিরপুর" },
    kind: "standard",
    capacity: 130,
    floorArea: 5460,
    openedAt: "2019-12-08",
    manager: { en: "Rakib Hasan", bn: "রাকিব হাসান" },
    phone: "+8801846035877",
    hue: "slate",
    initials: "M1",
    status: "live",
    map: { x: 0.34, y: 0.22 },
  },
  {
    id: "br_pallabi",
    slug: "pallabi",
    name: { en: "Pallabi", bn: "পল্লবী" },
    area: { en: "Mirpur", bn: "মিরপুর" },
    kind: "compact",
    capacity: 85,
    floorArea: 3570,
    openedAt: "2020-05-01",
    manager: { en: "Sabrina Islam", bn: "সাবরিনা ইসলাম" },
    phone: "+8801949755288",
    hue: "blue",
    initials: "P",
    status: "live",
    map: { x: 0.3, y: 0.19 },
  },
  {
    id: "br_bashundhara",
    slug: "bashundhara",
    name: { en: "Bashundhara", bn: "বসুন্ধরা" },
    area: { en: "Baridhara", bn: "বারিধারা" },
    kind: "flagship",
    capacity: 240,
    floorArea: 10080,
    openedAt: "2021-10-02",
    manager: { en: "Jubayer Khan", bn: "জুবায়ের খান" },
    phone: "+8801753474699",
    hue: "teal",
    initials: "B",
    status: "live",
    map: { x: 0.66, y: 0.26 },
  },
  {
    id: "br_gulshan-1",
    slug: "gulshan-1",
    name: { en: "Gulshan 1", bn: "গুলশান ১" },
    area: { en: "Gulshan", bn: "গুলশান" },
    kind: "standard",
    capacity: 155,
    floorArea: 6510,
    openedAt: "2022-03-03",
    manager: { en: "Nusrat Jahan", bn: "নুসরাত জাহান" },
    phone: "+8801857194110",
    hue: "green",
    initials: "G1",
    status: "live",
    map: { x: 0.6, y: 0.36 },
  },
  {
    id: "br_gulshan-2",
    slug: "gulshan-2",
    name: { en: "Gulshan 2", bn: "গুলশান ২" },
    area: { en: "Gulshan", bn: "গুলশান" },
    kind: "flagship",
    capacity: 190,
    floorArea: 7980,
    openedAt: "2023-08-04",
    manager: { en: "Tanvir Ahmed", bn: "তানভীর আহমেদ" },
    phone: "+8801960913521",
    hue: "purple",
    initials: "G2",
    status: "live",
    map: { x: 0.63, y: 0.32 },
  },
  {
    id: "br_banani",
    slug: "banani",
    name: { en: "Banani", bn: "বনানী" },
    area: { en: "Banani", bn: "বনানী" },
    kind: "standard",
    capacity: 145,
    floorArea: 6090,
    openedAt: "2024-01-05",
    manager: { en: "Rubaiya Haque", bn: "রুবাইয়া হক" },
    phone: "+8801764632932",
    hue: "magenta",
    initials: "B",
    status: "live",
    map: { x: 0.56, y: 0.3 },
  },
  {
    id: "br_baridhara-dohs",
    slug: "baridhara-dohs",
    name: { en: "Baridhara DOHS", bn: "বারিধারা ডিওএইচএস" },
    area: { en: "Baridhara", bn: "বারিধারা" },
    kind: "compact",
    capacity: 100,
    floorArea: 4200,
    openedAt: "2025-06-06",
    manager: { en: "Imran Kabir", bn: "ইমরান কবির" },
    phone: "+8801868352343",
    hue: "amber",
    initials: "BD",
    status: "live",
    map: { x: 0.68, y: 0.3 },
  },
  {
    id: "br_dhanmondi-27",
    slug: "dhanmondi-27",
    name: { en: "Dhanmondi 27", bn: "ধানমন্ডি ২৭" },
    area: { en: "Dhanmondi", bn: "ধানমন্ডি" },
    kind: "flagship",
    capacity: 185,
    floorArea: 7770,
    openedAt: "2019-11-07",
    manager: { en: "Sadia Rahman", bn: "সাদিয়া রহমান" },
    phone: "+8801972071754",
    hue: "rose",
    initials: "D2",
    status: "live",
    map: { x: 0.32, y: 0.5 },
  },
  {
    id: "br_dhanmondi-32",
    slug: "dhanmondi-32",
    name: { en: "Dhanmondi 32", bn: "ধানমন্ডি ৩২" },
    area: { en: "Dhanmondi", bn: "ধানমন্ডি" },
    kind: "standard",
    capacity: 135,
    floorArea: 5670,
    openedAt: "2020-04-08",
    manager: { en: "Mahfuz Alam", bn: "মাহফুজ আলম" },
    phone: "+8801775791165",
    hue: "slate",
    initials: "D3",
    status: "live",
    map: { x: 0.3, y: 0.46 },
  },
  {
    id: "br_mohammadpur",
    slug: "mohammadpur",
    name: { en: "Mohammadpur", bn: "মোহাম্মদপুর" },
    area: { en: "Mohammadpur", bn: "মোহাম্মদপুর" },
    kind: "standard",
    capacity: 125,
    floorArea: 5250,
    openedAt: "2021-09-01",
    manager: { en: "Farzana Akter", bn: "ফারজানা আক্তার" },
    phone: "+8801879510576",
    hue: "blue",
    initials: "M",
    status: "live",
    map: { x: 0.24, y: 0.44 },
  },
  {
    id: "br_shyamoli",
    slug: "shyamoli",
    name: { en: "Shyamoli", bn: "শ্যামলী" },
    area: { en: "Mohammadpur", bn: "মোহাম্মদপুর" },
    kind: "compact",
    capacity: 88,
    floorArea: 3696,
    openedAt: "2022-02-02",
    manager: { en: "Rakib Hasan", bn: "রাকিব হাসান" },
    phone: "+8801983229987",
    hue: "teal",
    initials: "S",
    status: "live",
    map: { x: 0.26, y: 0.4 },
  },
  {
    id: "br_badda",
    slug: "badda",
    name: { en: "Badda", bn: "বাড্ডা" },
    area: { en: "Badda", bn: "বাড্ডা" },
    kind: "standard",
    capacity: 130,
    floorArea: 5460,
    openedAt: "2023-07-03",
    manager: { en: "Sabrina Islam", bn: "সাবরিনা ইসলাম" },
    phone: "+8801786949398",
    hue: "green",
    initials: "B",
    status: "live",
    map: { x: 0.64, y: 0.42 },
  },
  {
    id: "br_rampura",
    slug: "rampura",
    name: { en: "Rampura", bn: "রামপুরা" },
    area: { en: "Rampura", bn: "রামপুরা" },
    kind: "compact",
    capacity: 92,
    floorArea: 3864,
    openedAt: "2024-12-04",
    manager: { en: "Jubayer Khan", bn: "জুবায়ের খান" },
    phone: "+8801890668809",
    hue: "purple",
    initials: "R",
    status: "live",
    map: { x: 0.6, y: 0.48 },
  },
  {
    id: "br_khilgaon",
    slug: "khilgaon",
    name: { en: "Khilgaon", bn: "খিলগাঁও" },
    area: { en: "Khilgaon", bn: "খিলগাঁও" },
    kind: "standard",
    capacity: 120,
    floorArea: 5040,
    openedAt: "2025-05-05",
    manager: { en: "Nusrat Jahan", bn: "নুসরাত জাহান" },
    phone: "+8801994388220",
    hue: "magenta",
    initials: "K",
    status: "live",
    map: { x: 0.54, y: 0.55 },
  },
  {
    id: "br_bailey-road",
    slug: "bailey-road",
    name: { en: "Bailey Road", bn: "বেইলি রোড" },
    area: { en: "Ramna", bn: "রমনা" },
    kind: "standard",
    capacity: 128,
    floorArea: 5376,
    openedAt: "2019-10-06",
    manager: { en: "Tanvir Ahmed", bn: "তানভীর আহমেদ" },
    phone: "+8801798107631",
    hue: "amber",
    initials: "BR",
    status: "live",
    map: { x: 0.44, y: 0.56 },
  },
  {
    id: "br_motijheel",
    slug: "motijheel",
    name: { en: "Motijheel", bn: "মতিঝিল" },
    area: { en: "Motijheel", bn: "মতিঝিল" },
    kind: "compact",
    capacity: 95,
    floorArea: 3990,
    openedAt: "2020-03-07",
    manager: { en: "Rubaiya Haque", bn: "রুবাইয়া হক" },
    phone: "+8801821827043",
    hue: "rose",
    initials: "M",
    status: "live",
    map: { x: 0.46, y: 0.66 },
  },
  {
    id: "br_wari",
    slug: "wari",
    name: { en: "Wari", bn: "ওয়ারী" },
    area: { en: "Wari", bn: "ওয়ারী" },
    kind: "compact",
    capacity: 82,
    floorArea: 3444,
    openedAt: "2021-08-08",
    manager: { en: "Imran Kabir", bn: "ইমরান কবির" },
    phone: "+8801925546454",
    hue: "slate",
    initials: "W",
    status: "live",
    map: { x: 0.4, y: 0.7 },
  },
  {
    id: "br_jatrabari",
    slug: "jatrabari",
    name: { en: "Jatrabari", bn: "যাত্রাবাড়ী" },
    area: { en: "Jatrabari", bn: "যাত্রাবাড়ী" },
    kind: "standard",
    capacity: 115,
    floorArea: 4830,
    openedAt: "2022-01-01",
    manager: { en: "Sadia Rahman", bn: "সাদিয়া রহমান" },
    phone: "+8801729265865",
    hue: "blue",
    initials: "J",
    status: "live",
    map: { x: 0.5, y: 0.78 },
  },
  {
    id: "br_mugda",
    slug: "mugda",
    name: { en: "Mugda", bn: "মুগদা" },
    area: { en: "Mugda", bn: "মুগদা" },
    kind: "compact",
    capacity: 80,
    floorArea: 3360,
    openedAt: "2023-06-02",
    manager: { en: "Mahfuz Alam", bn: "মাহফুজ আলম" },
    phone: "+8801832985276",
    hue: "teal",
    initials: "M",
    status: "live",
    map: { x: 0.55, y: 0.66 },
  },
  {
    id: "br_savar",
    slug: "savar",
    name: { en: "Savar", bn: "সাভার" },
    area: { en: "Savar", bn: "সাভার" },
    kind: "standard",
    capacity: 118,
    floorArea: 4956,
    openedAt: "2024-11-03",
    manager: { en: "Farzana Akter", bn: "ফারজানা আক্তার" },
    phone: "+8801936704687",
    hue: "green",
    initials: "S",
    status: "live",
    map: { x: 0.08, y: 0.3 },
  },
  {
    id: "br_ashulia",
    slug: "ashulia",
    name: { en: "Ashulia", bn: "আশুলিয়া" },
    area: { en: "Ashulia", bn: "আশুলিয়া" },
    kind: "compact",
    capacity: 86,
    floorArea: 3612,
    openedAt: "2025-04-04",
    manager: { en: "Rakib Hasan", bn: "রাকিব হাসান" },
    phone: "+8801740424098",
    hue: "purple",
    initials: "A",
    status: "soft-launch",
    map: { x: 0.12, y: 0.16 },
  },
  {
    id: "br_tongi",
    slug: "tongi",
    name: { en: "Tongi", bn: "টঙ্গী" },
    area: { en: "Gazipur", bn: "গাজীপুর" },
    kind: "standard",
    capacity: 122,
    floorArea: 5124,
    openedAt: "2019-09-05",
    manager: { en: "Sabrina Islam", bn: "সাবরিনা ইসলাম" },
    phone: "+8801844143509",
    hue: "magenta",
    initials: "T",
    status: "soft-launch",
    map: { x: 0.52, y: 0.03 },
  },
  {
    id: "br_narayanganj",
    slug: "narayanganj",
    name: { en: "Narayanganj", bn: "নারায়ণগঞ্জ" },
    area: { en: "Narayanganj", bn: "নারায়ণগঞ্জ" },
    kind: "flagship",
    capacity: 175,
    floorArea: 7350,
    openedAt: "2020-02-06",
    manager: { en: "Jubayer Khan", bn: "জুবায়ের খান" },
    phone: "+8801947862920",
    hue: "amber",
    initials: "N",
    status: "fit-out",
    map: { x: 0.72, y: 0.9 },
  },
]

export const DEFAULT_BRANCH_ID = BRANCHES[0].id

/** Sentinel for the master-admin roll-up scope. */
export const ALL_BRANCHES = "all"

export function getBranch(id: string): Branch {
  return BRANCHES.find((b) => b.id === id) ?? BRANCHES[0]
}

export const LIVE_BRANCHES = BRANCHES.filter((b) => b.status === "live")
